// Importar as novas raças
import { additionalDogBreeds } from "./dog-breeds-additions"

// Banco de dados com raças de cachorro
export const dogBreeds = [
  {
    id: 1,
    name: "Japanese Chin",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Japanese Chin é um cão de companhia elegante e charmoso. Originário do Japão, é conhecido por seu temperamento doce e personalidade cativante. É um cão pequeno, com pelagem longa e sedosa, e expressão facial única que lembra um gato.",
    image: "/images/breeds/japanese-chin.jpeg",
    energyLevel: "Baixo a Médio",
    coat: "Longo",
    trainability: 7,
    childFriendly: 8,
    exerciseNeeds: 4,
    groomingNeeds: 7,
    shedding: 5,
    breeders: [
      {
        name: "My Little Chin",
        location: "São Paulo, SP",
        website: "https://www.japanesechin.com.br/",
      },
      {
        name: "Canil Oriental Brasil",
        location: "Rio de Janeiro, RJ",
        website: "https://www.canilorientalbrasil.com.br",
      },
    ],
  },
  {
    id: 2,
    name: "Labrador Retriever",
    size: "Grande",
    purpose: "Companhia",
    description:
      "O Labrador Retriever é uma das raças mais populares do mundo. Conhecido por sua inteligência, temperamento amigável e versatilidade. São excelentes cães de família, muito pacientes com crianças e adaptáveis a diferentes ambientes.",
    image: "/images/breeds/labrador-retriever.jpeg",
    energyLevel: "Alto",
    coat: "Curto",
    trainability: 9,
    childFriendly: 10,
    exerciseNeeds: 8,
    groomingNeeds: 4,
    shedding: 8,
    breeders: [
      {
        name: "Canil Gold Retriever",
        location: "Campinas, SP",
        website: "https://www.canilgoldretriever.com.br",
      },
      {
        name: "Labrador Elite",
        location: "Belo Horizonte, MG",
        website: "https://www.labradorelite.com.br",
      },
    ],
  },
  {
    id: 3,
    name: "Bulldog Francês",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Bulldog Francês é um cão compacto e musculoso, com orelhas de morcego características. Apesar de sua aparência robusta, é um cão de companhia afetuoso e brincalhão, que se adapta bem à vida em apartamentos.",
    image: "/images/breeds/bulldog-frances.jpeg",
    energyLevel: "Médio",
    coat: "Curto",
    trainability: 6,
    childFriendly: 8,
    exerciseNeeds: 5,
    groomingNeeds: 3,
    shedding: 4,
    breeders: [
      {
        name: "Canil Petit Frenchie",
        location: "São Paulo, SP",
        website: "https://www.petitfrenchie.com.br",
      },
      {
        name: "Bulldog Francês Brasil",
        location: "Curitiba, PR",
        website: "https://www.bulldogfrancesbrasil.com.br",
      },
    ],
  },
  {
    id: 4,
    name: "Pastor Alemão",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Pastor Alemão é uma raça versátil, conhecida por sua inteligência, lealdade e coragem. São excelentes cães de trabalho, utilizados em funções policiais, militares e de resgate. Como cães de família, são protetores e devotados.",
    image: "/images/breeds/pastor-alemao.jpeg",
    energyLevel: "Alto",
    coat: "Médio",
    trainability: 9,
    childFriendly: 7,
    exerciseNeeds: 8,
    groomingNeeds: 6,
    shedding: 9,
    breeders: [
      {
        name: "Canil von der Haus",
        location: "Porto Alegre, RS",
        website: "https://www.canilvonderhaus.com.br",
      },
      {
        name: "Elite Shepherd",
        location: "Brasília, DF",
        website: "https://www.eliteshepherd.com.br",
      },
    ],
  },
  {
    id: 5,
    name: "Golden Retriever",
    size: "Grande",
    purpose: "Companhia",
    description:
      "O Golden Retriever é conhecido por seu temperamento amigável e tolerante. São cães inteligentes, leais e ansiosos para agradar, o que os torna fáceis de treinar. Excelentes com crianças e outros animais, são companheiros perfeitos para famílias ativas.",
    image: "/images/breeds/golden-retriever.jpeg",
    energyLevel: "Alto",
    coat: "Médio a Longo",
    trainability: 9,
    childFriendly: 10,
    exerciseNeeds: 7,
    groomingNeeds: 6,
    shedding: 8,
    breeders: [
      {
        name: "Golden Paradise",
        location: "São Paulo, SP",
        website: "https://www.goldenparadise.com.br",
      },
      {
        name: "Canil Gold Star",
        location: "Florianópolis, SC",
        website: "https://www.canilgoldstar.com.br",
      },
    ],
  },
  {
    id: 6,
    name: "Shih Tzu",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Shih Tzu é um cão de companhia por excelência, conhecido por seu temperamento afetuoso e personalidade extrovertida. Apesar do tamanho pequeno, são cães confiantes e alertas. Adaptam-se bem a diferentes ambientes, incluindo apartamentos.",
    image: "/images/breeds/shih-tzu.jpeg",
    energyLevel: "Médio",
    coat: "Longo",
    trainability: 6,
    childFriendly: 8,
    exerciseNeeds: 4,
    groomingNeeds: 9,
    shedding: 3,
    breeders: [
      {
        name: "Canil Imperial Shih Tzu",
        location: "Rio de Janeiro, RJ",
        website: "https://www.imperialshihtzu.com.br",
      },
      {
        name: "Royal Shih Tzu",
        location: "Belo Horizonte, MG",
        website: "https://www.royalshihtzu.com.br",
      },
    ],
  },
  {
    id: 7,
    name: "Rottweiler",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Rottweiler é um cão poderoso e robusto, conhecido por sua força, inteligência e lealdade. Com treinamento adequado, são cães equilibrados e confiáveis. São excelentes guardiões, mas também podem ser companheiros afetuosos para famílias experientes.",
    image: "/images/breeds/rottweiler.jpeg",
    energyLevel: "Médio a Alto",
    coat: "Curto",
    trainability: 8,
    childFriendly: 6,
    exerciseNeeds: 7,
    groomingNeeds: 3,
    shedding: 7,
    breeders: [
      {
        name: "Canil von Rott",
        location: "Curitiba, PR",
        website: "https://www.canilvonrott.com.br",
      },
      {
        name: "Rottweiler Elite",
        location: "Goiânia, GO",
        website: "https://www.rottweilerelite.com.br",
      },
    ],
  },
  {
    id: 8,
    name: "Poodle",
    size: "Vários (Toy, Miniatura, Standard)",
    purpose: "Companhia",
    description:
      "O Poodle é uma das raças mais inteligentes, disponível em três tamanhos diferentes. São cães ativos, orgulhosos e muito inteligentes. Apesar da reputação de sofisticação, são cães brincalhões e afetuosos, excelentes para famílias.",
    image: "/images/breeds/poodle.jpeg",
    energyLevel: "Alto",
    coat: "Longo (Cacheado)",
    trainability: 10,
    childFriendly: 9,
    exerciseNeeds: 7,
    groomingNeeds: 10,
    shedding: 1,
    breeders: [
      {
        name: "Canil Poodle Elegance",
        location: "São Paulo, SP",
        website: "https://www.poodleelegance.com.br",
      },
      {
        name: "Royal Poodles",
        location: "Salvador, BA",
        website: "https://www.royalpoodles.com.br",
      },
    ],
  },
  {
    id: 9,
    name: "Buldogue Inglês",
    size: "Médio",
    purpose: "Companhia",
    description:
      "O Buldogue Inglês é conhecido por sua aparência distintiva e temperamento calmo e amigável. São cães de baixa energia, que se adaptam bem à vida em apartamentos. Apesar da aparência intimidadora, são gentis e afetuosos com a família.",
    image: "/images/breeds/buldogue-ingles.jpeg",
    energyLevel: "Baixo",
    coat: "Curto",
    trainability: 5,
    childFriendly: 8,
    exerciseNeeds: 3,
    groomingNeeds: 5,
    shedding: 5,
    breeders: [
      {
        name: "Canil British Bulldog",
        location: "Rio de Janeiro, RJ",
        website: "https://www.britishbulldog.com.br",
      },
      {
        name: "English Bulldog Brasil",
        location: "Brasília, DF",
        website: "https://www.englishbulldogbrasil.com.br",
      },
    ],
  },
  {
    id: 10,
    name: "Border Collie",
    size: "Médio",
    purpose: "Esportes e Hobby",
    description:
      "O Border Collie é considerado a raça mais inteligente do mundo. São cães extremamente ativos, ágeis e com grande capacidade de aprendizado. Precisam de muita atividade física e mental, sendo ideais para famílias ativas que praticam esportes.",
    image: "/images/breeds/border-collie.jpeg",
    energyLevel: "Muito Alto",
    coat: "Médio",
    trainability: 10,
    childFriendly: 7,
    exerciseNeeds: 10,
    groomingNeeds: 6,
    shedding: 7,
    breeders: [
      {
        name: "Canil Border Elite",
        location: "Curitiba, PR",
        website: "https://www.borderelite.com.br",
      },
      {
        name: "Working Border Collies",
        location: "Porto Alegre, RS",
        website: "https://www.workingbordercollies.com.br",
      },
    ],
  },
  {
    id: 11,
    name: "Beagle",
    size: "Pequeno a Médio",
    purpose: "Companhia",
    description:
      "O Beagle é um cão alegre, curioso e cheio de energia. Originalmente criado para caça, hoje é principalmente um cão de companhia. São excelentes com crianças e outros animais, mas podem ser teimosos durante o treinamento.",
    image: "/images/breeds/beagle.jpeg",
    energyLevel: "Alto",
    coat: "Curto",
    trainability: 5,
    childFriendly: 9,
    exerciseNeeds: 8,
    groomingNeeds: 3,
    shedding: 6,
    breeders: [
      {
        name: "Canil Beagle Brasil",
        location: "São Paulo, SP",
        website: "https://www.beaglebrasil.com.br",
      },
      {
        name: "Happy Beagles",
        location: "Belo Horizonte, MG",
        website: "https://www.happybeagles.com.br",
      },
    ],
  },
  {
    id: 12,
    name: "Dachshund (Salsicha)",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Dachshund, também conhecido como cão salsicha, é corajoso, alerta e cheio de personalidade. Apesar do tamanho pequeno, são excelentes cães de guarda devido ao seu latido alto e temperamento vigilante.",
    image: "/images/breeds/dachshund.jpg",
    energyLevel: "Médio",
    coat: "Curto, Longo ou Duro",
    trainability: 5,
    childFriendly: 7,
    exerciseNeeds: 5,
    groomingNeeds: 4,
    shedding: 4,
    breeders: [
      {
        name: "Canil Dachshund Brasil",
        location: "Campinas, SP",
        website: "https://www.dachshundbrasil.com.br",
      },
      {
        name: "Salsichinhas Felizes",
        location: "Florianópolis, SC",
        website: "https://www.salsichinhasfelizes.com.br",
      },
    ],
  },
  {
    id: 13,
    name: "Terra Nova",
    size: "Gigante",
    purpose: "Companhia e Esporte",
    description:
      "O Terra Nova é um cão gigante, conhecido por sua força, nobreza e temperamento doce. Originalmente criado para trabalhar com pescadores, é um excelente nadador e tem instinto de salvamento. Apesar do tamanho, é gentil e paciente com crianças.",
    image: "/images/breeds/terra-nova.jpg",
    energyLevel: "Médio",
    coat: "Longo e Denso",
    trainability: 7,
    childFriendly: 9,
    exerciseNeeds: 5,
    groomingNeeds: 8,
    shedding: 8,
    breeders: [
      {
        name: "Prince of the Dogs",
        location: "São Paulo, SP",
        website: "https://www.princeofthedogs.com.br",
      },
      {
        name: "Canil Terra Nova Brasil",
        location: "Porto Alegre, RS",
        website: "https://www.terranovabrasil.com.br",
      },
    ],
  },
  {
    id: 14,
    name: "Kuvasz",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Kuvasz é um cão de guarda e proteção originário da Hungria. É conhecido por sua independência, coragem e lealdade à família. Com pelagem branca e densa, é um cão imponente e elegante, que requer um dono experiente e consistente.",
    image: "/images/breeds/kuvasz.jpg",
    energyLevel: "Médio a Alto",
    coat: "Médio a Longo",
    trainability: 6,
    childFriendly: 7,
    exerciseNeeds: 7,
    groomingNeeds: 6,
    shedding: 7,
    breeders: [
      {
        name: "Prince of the Dogs",
        location: "São Paulo, SP",
        website: "https://www.princeofthedogs.com.br",
      },
      {
        name: "Canil Kuvasz Elite",
        location: "Curitiba, PR",
        website: "https://www.kuvaszelbrasil.com.br",
      },
    ],
  },
  {
    id: 15,
    name: "Coton de Tulear",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Coton de Tulear é um cão de companhia alegre e brincalhão, originário de Madagascar. Conhecido por sua pelagem branca, macia e semelhante ao algodão (daí o nome 'Coton'). São cães afetuosos, inteligentes e muito apegados aos donos.",
    image: "/images/breeds/coton-de-tulear.webp",
    energyLevel: "Médio",
    coat: "Longo",
    trainability: 8,
    childFriendly: 9,
    exerciseNeeds: 5,
    groomingNeeds: 8,
    shedding: 2,
    breeders: [
      {
        name: "Canil Coton Brasil",
        location: "São Paulo, SP",
        website: "https://www.cotonbrasil.com.br",
      },
      {
        name: "Coton Elite",
        location: "Rio de Janeiro, RJ",
        website: "https://www.cotonelite.com.br",
      },
    ],
  },
  {
    id: 16,
    name: "Pastor Belga Malinois",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Pastor Belga Malinois é um cão de trabalho excepcional, conhecido por sua inteligência, energia e capacidade de aprendizado. Muito utilizado em forças policiais e militares devido à sua agilidade e obediência. Requer um dono experiente e ativo.",
    image: "/images/breeds/pastor-belga-malinois.jpeg",
    energyLevel: "Muito Alto",
    coat: "Curto",
    trainability: 9,
    childFriendly: 6,
    exerciseNeeds: 10,
    groomingNeeds: 4,
    shedding: 6,
    breeders: [
      {
        name: "Canil K9 Elite",
        location: "Brasília, DF",
        website: "https://www.k9elite.com.br",
      },
      {
        name: "Malinois Brasil",
        location: "Curitiba, PR",
        website: "https://www.malinoisbrasil.com.br",
      },
    ],
  },
  {
    id: 17,
    name: "Cane Corso",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Cane Corso é um cão italiano de porte grande, musculoso e imponente. São cães inteligentes, leais e protetores. Com treinamento adequado, são equilibrados e excelentes guardiões da família. Precisam de socialização desde filhotes.",
    image: "/images/breeds/cane-corso.jpg",
    energyLevel: "Médio a Alto",
    coat: "Curto",
    trainability: 7,
    childFriendly: 7,
    exerciseNeeds: 7,
    groomingNeeds: 2,
    shedding: 5,
    breeders: [
      {
        name: "Canil Cane Corso Brasil",
        location: "São Paulo, SP",
        website: "https://www.canecorsobrasil.com.br",
      },
      {
        name: "Cane Corso Elite",
        location: "Belo Horizonte, MG",
        website: "https://www.canecorsoelite.com.br",
      },
    ],
  },
  {
    id: 18,
    name: "Maltês",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Maltês é um cão pequeno e elegante, com pelagem branca longa e sedosa. São cães afetuosos, brincalhões e muito sociáveis. Apesar do tamanho diminuto, são corajosos e alertas. Excelentes cães de companhia para famílias e idosos.",
    image: "/images/breeds/maltes.jpg",
    energyLevel: "Médio",
    coat: "Longo",
    trainability: 7,
    childFriendly: 8,
    exerciseNeeds: 4,
    groomingNeeds: 9,
    shedding: 2,
    breeders: [
      {
        name: "Canil Maltês Elite",
        location: "São Paulo, SP",
        website: "https://www.malteselite.com.br",
      },
      {
        name: "Royal Maltês",
        location: "Rio de Janeiro, RJ",
        website: "https://www.royalmaltes.com.br",
      },
    ],
  },
  {
    id: 19,
    name: "Cavalier King Charles Spaniel",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Cavalier King Charles Spaniel é um cão doce, gentil e afetuoso. Com olhos grandes e expressivos, são conhecidos por seu temperamento amigável e adaptável. Excelentes companheiros para famílias e idosos, se dão bem com crianças e outros animais.",
    image: "/images/breeds/cavalier-king-charles-spaniel.jpg",
    energyLevel: "Médio",
    coat: "Médio a Longo",
    trainability: 8,
    childFriendly: 9,
    exerciseNeeds: 5,
    groomingNeeds: 7,
    shedding: 4,
    breeders: [
      {
        name: "Canil Cavalier Brasil",
        location: "São Paulo, SP",
        website: "https://www.cavalierbrasil.com.br",
      },
      {
        name: "Royal Cavaliers",
        location: "Belo Horizonte, MG",
        website: "https://www.royalcavaliers.com.br",
      },
    ],
  },
  {
    id: 20,
    name: "Bichon Frisé",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Bichon Frisé é um cão pequeno e alegre, com pelagem branca e fofa. São cães brincalhões, afetuosos e muito sociáveis. Conhecidos por seu temperamento doce e adaptável, são excelentes para famílias com crianças e para apartamentos.",
    image: "/images/breeds/bichon-frise.jpg",
    energyLevel: "Médio",
    coat: "Longo (Cacheado)",
    trainability: 8,
    childFriendly: 9,
    exerciseNeeds: 5,
    groomingNeeds: 9,
    shedding: 1,
    breeders: [
      {
        name: "Canil Bichon Elite",
        location: "São Paulo, SP",
        website: "https://www.bichonelite.com.br",
      },
      {
        name: "Bichon Frisé Brasil",
        location: "Rio de Janeiro, RJ",
        website: "https://www.bichonfrisebrasil.com.br",
      },
    ],
  },
  {
    id: 21,
    name: "Dogue Alemão",
    size: "Gigante",
    purpose: "Companhia",
    description:
      "O Dogue Alemão é um dos maiores cães do mundo, conhecido como o 'Apolo dos cães'. Apesar do tamanho impressionante, são gentis, pacientes e afetuosos. Excelentes com crianças, mas precisam de espaço devido ao seu porte gigante.",
    image: "/images/breeds/dogue-alemao.jpg",
    energyLevel: "Médio",
    coat: "Curto",
    trainability: 7,
    childFriendly: 8,
    exerciseNeeds: 6,
    groomingNeeds: 3,
    shedding: 5,
    breeders: [
      {
        name: "Canil Great Dane Brasil",
        location: "São Paulo, SP",
        website: "https://www.greatdanebrasil.com.br",
      },
      {
        name: "Dogue Alemão Elite",
        location: "Curitiba, PR",
        website: "https://www.doguealemaoelite.com.br",
      },
    ],
  },
  {
    id: 22,
    name: "Lhasa Apso",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Lhasa Apso é um cão originário do Tibete, criado como cão de guarda em mosteiros. São independentes, alertas e leais. Possuem pelagem longa e densa que requer cuidados regulares. São excelentes cães de companhia, especialmente para apartamentos.",
    image: "/images/breeds/lhasa-apso.jpg",
    energyLevel: "Médio",
    coat: "Longo",
    trainability: 6,
    childFriendly: 7,
    exerciseNeeds: 4,
    groomingNeeds: 9,
    shedding: 3,
    breeders: [
      {
        name: "Canil Lhasa Brasil",
        location: "São Paulo, SP",
        website: "https://www.lhasabrasil.com.br",
      },
      {
        name: "Lhasa Apso Elite",
        location: "Rio de Janeiro, RJ",
        website: "https://www.lhasaapsoelite.com.br",
      },
    ],
  },
  {
    id: 23,
    name: "Pequinês",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Pequinês é um cão de origem chinesa, criado como cão de companhia da realeza. São independentes, dignos e leais. Possuem uma aparência distinta com face achatada e pelagem abundante. Adaptam-se bem a apartamentos e são bons companheiros para idosos.",
    image: "/images/breeds/pequines.jpg",
    energyLevel: "Baixo a Médio",
    coat: "Longo",
    trainability: 5,
    childFriendly: 6,
    exerciseNeeds: 3,
    groomingNeeds: 8,
    shedding: 5,
    breeders: [
      {
        name: "Canil Pequinês Brasil",
        location: "São Paulo, SP",
        website: "https://www.pequinesbrasil.com.br",
      },
      {
        name: "Royal Pequinês",
        location: "Belo Horizonte, MG",
        website: "https://www.royalpequines.com.br",
      },
    ],
  },
  {
    id: 24,
    name: "Spitz Alemão",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Spitz Alemão, também conhecido como Lulu da Pomerânia, é um cão pequeno e vivo, com pelagem fofa e expressão raposa. São inteligentes, alertas e cheios de personalidade. Apesar do tamanho pequeno, são corajosos e podem ser bons cães de guarda.",
    image: "/images/breeds/spitz-alemao.jpg",
    energyLevel: "Alto",
    coat: "Longo",
    trainability: 6,
    childFriendly: 6,
    exerciseNeeds: 5,
    groomingNeeds: 8,
    shedding: 7,
    breeders: [
      {
        name: "Canil Spitz Brasil",
        location: "São Paulo, SP",
        website: "https://www.spitzbrasil.com.br",
      },
      {
        name: "Pomeranian Elite",
        location: "Rio de Janeiro, RJ",
        website: "https://www.pomeranianelite.com.br",
      },
    ],
  },
  {
    id: 25,
    name: "Samoieda",
    size: "Médio a Grande",
    purpose: "Companhia e Esporte",
    description:
      "O Samoieda é um cão nórdico de pelagem branca e fofa, conhecido por seu sorriso característico. Originalmente criados para puxar trenós e pastorear renas, são cães amigáveis, inteligentes e cheios de energia. Excelentes para famílias ativas.",
    image: "/images/breeds/samoieda.jpg",
    energyLevel: "Alto",
    coat: "Longo e Denso",
    trainability: 7,
    childFriendly: 9,
    exerciseNeeds: 8,
    groomingNeeds: 8,
    shedding: 9,
    breeders: [
      {
        name: "Canil Samoieda Brasil",
        location: "Campos do Jordão, SP",
        website: "https://www.samoiedabrasil.com.br",
      },
      {
        name: "Samoyed Elite",
        location: "Gramado, RS",
        website: "https://www.samoyedelite.com.br",
      },
    ],
  },
  {
    id: 26,
    name: "Schnauzer",
    size: "Vários (Miniatura, Standard, Gigante)",
    purpose: "Companhia e Guarda",
    description:
      "O Schnauzer é uma raça alemã disponível em três tamanhos. São cães inteligentes, alertas e enérgicos, com barba e sobrancelhas características. Leais à família e bons cães de guarda, são também excelentes companheiros para famílias ativas.",
    image: "/images/breeds/schnauzer.jpg",
    energyLevel: "Alto",
    coat: "Duro",
    trainability: 8,
    childFriendly: 8,
    exerciseNeeds: 7,
    groomingNeeds: 7,
    shedding: 2,
    breeders: [
      {
        name: "Canil Schnauzer Brasil",
        location: "São Paulo, SP",
        website: "https://www.schnauzerbrasil.com.br",
      },
      {
        name: "Schnauzer Elite",
        location: "Curitiba, PR",
        website: "https://www.schnauzerelite.com.br",
      },
    ],
  },
  {
    id: 27,
    name: "Fila Brasileiro",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Fila Brasileiro é um cão de guarda nativo do Brasil, conhecido por sua lealdade, coragem e instinto protetor. São cães fortes, musculosos e determinados. Extremamente devotados à família, mas reservados com estranhos. Requerem socialização adequada e dono experiente.",
    image: "/images/breeds/fila-brasileiro.jpg",
    energyLevel: "Médio",
    coat: "Curto",
    trainability: 6,
    childFriendly: 7,
    exerciseNeeds: 6,
    groomingNeeds: 3,
    shedding: 6,
    breeders: [
      {
        name: "Canil Fila Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.filabrasil.com.br",
      },
      {
        name: "Fila Brasileiro Elite",
        location: "São Paulo, SP",
        website: "https://www.filabrasileiro.com.br",
      },
    ],
  },
  {
    id: 31,
    name: "Cão dos Pirineus",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Cão dos Pirineus, ou Montanha dos Pirineus, é um cão de guarda de rebanho majestoso e imponente. Com pelagem branca e densa, é conhecido por seu temperamento calmo e protetor. Apesar do tamanho, é gentil com a família e paciente com crianças, mas mantém-se alerta contra estranhos.",
    image: "/images/breeds/cao-dos-pirineus.jpg",
    energyLevel: "Médio",
    coat: "Longo e Denso",
    trainability: 6,
    childFriendly: 8,
    exerciseNeeds: 5,
    groomingNeeds: 8,
    shedding: 8,
    breeders: [
      {
        name: "Canil Montanha Branca",
        location: "Santa Catarina, SC",
        website: "https://www.canilmontanhabranca.com.br",
      },
      {
        name: "Pirineus Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.pirineusbrasil.com.br",
      },
    ],
  },
  // Adicionar as novas raças
  ...additionalDogBreeds,
]
