// Novas raças para adicionar ao banco de dados
export const additionalDogBreeds = [
  {
    id: 28,
    name: "Doberman",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Doberman é um cão elegante, musculoso e atlético, conhecido por sua inteligência, lealdade e capacidade de trabalho. Originalmente criado como cão de guarda pessoal, hoje é um excelente cão de família quando bem socializado e treinado. Requer exercício regular e estimulação mental.",
    image: "/images/breeds/doberman.jpg",
    energyLevel: "Alto",
    coat: "Curto",
    trainability: 9,
    childFriendly: 7,
    exerciseNeeds: 8,
    groomingNeeds: 2,
    shedding: 4,
    breeders: [
      {
        name: "Canil von Dobermann",
        location: "São Paulo, SP",
        website: "https://www.canilvondobermann.com.br",
      },
      {
        name: "Elite Doberman",
        location: "Curitiba, PR",
        website: "https://www.elitedoberman.com.br",
      },
    ],
  },
  {
    id: 29,
    name: "Pastor do Cáucaso",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Pastor do Cáucaso é um cão de guarda poderoso e territorial, originário da região do Cáucaso. Com aparência imponente e temperamento independente, é extremamente protetor de sua família e território. Requer socialização precoce e um dono experiente com pulso firme.",
    image: "/images/breeds/pastor-do-caucaso.jpg",
    energyLevel: "Médio",
    coat: "Longo e Denso",
    trainability: 5,
    childFriendly: 6,
    exerciseNeeds: 6,
    groomingNeeds: 7,
    shedding: 8,
    breeders: [
      {
        name: "Canil Montanha do Cáucaso",
        location: "Minas Gerais, MG",
        website: "https://www.canilmontanhadocaucaso.com.br",
      },
      {
        name: "Canil Guardião do Cáucaso",
        location: "Rio Grande do Sul, RS",
        website: "https://www.guardiãodocaucaso.com.br",
      },
    ],
  },
  {
    id: 30,
    name: "Alabai (Pastor da Ásia Central)",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Alabai, também conhecido como Pastor da Ásia Central, é uma raça antiga usada para proteger rebanhos e propriedades. É um cão robusto, independente e territorial, com forte instinto de proteção. Requer socialização cuidadosa e um dono experiente que entenda seu comportamento natural.",
    image: "/images/breeds/alabai.jpg",
    energyLevel: "Médio",
    coat: "Médio a Longo",
    trainability: 4,
    childFriendly: 5,
    exerciseNeeds: 5,
    groomingNeeds: 6,
    shedding: 7,
    breeders: [
      {
        name: "Canil Alabai Brasil",
        location: "São Paulo, SP",
        website: "https://www.alabaibrasil.com.br",
      },
      {
        name: "Central Asian Shepherd",
        location: "Paraná, PR",
        website: "https://www.centralasianshepherd.com.br",
      },
    ],
  },
  {
    id: 31,
    name: "Cão dos Pirineus",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Cão dos Pirineus, ou Montanha dos Pirineus, é um cão de guarda de rebanho majestoso e imponente. Com pelagem branca e densa, é conhecido por seu temperamento calmo e protetor. Apesar do tamanho, é gentil com a família e paciente com crianças, mas mantém-se alerta contra estranhos.",
    image: "/images/breeds/cao-dos-pirineus.jpg",
    energyLevel: "Médio",
    coat: "Longo e Denso",
    trainability: 6,
    childFriendly: 8,
    exerciseNeeds: 5,
    groomingNeeds: 8,
    shedding: 8,
    breeders: [
      {
        name: "Canil Montanha Branca",
        location: "Santa Catarina, SC",
        website: "https://www.canilmontanhabranca.com.br",
      },
      {
        name: "Pirineus Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.pirineusbrasil.com.br",
      },
    ],
  },
  {
    id: 32,
    name: "Affenpinscher",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Affenpinscher é um cão pequeno e destemido, conhecido como 'macaquinho' devido à sua aparência facial. Apesar do tamanho diminuto, tem personalidade forte e corajosa. É um cão alerta, curioso e brincalhão, que se adapta bem à vida em apartamentos.",
    image: "/images/breeds/affenpinscher.jpg",
    energyLevel: "Médio a Alto",
    coat: "Áspero",
    trainability: 6,
    childFriendly: 5,
    exerciseNeeds: 5,
    groomingNeeds: 7,
    shedding: 2,
    breeders: [
      {
        name: "Canil Pequenos Notáveis",
        location: "São Paulo, SP",
        website: "https://www.pequenosnotaveis.com.br",
      },
      {
        name: "Affenpinscher Brasil",
        location: "Rio de Janeiro, RJ",
        website: "https://www.affenpinscherbrasil.com.br",
      },
    ],
  },
  {
    id: 33,
    name: "Griffon de Bruxelas",
    size: "Pequeno",
    purpose: "Companhia",
    description:
      "O Griffon de Bruxelas é um cão pequeno com expressão quase humana e personalidade vibrante. Extremamente apegado aos donos, é afetuoso, alerta e cheio de energia. Adapta-se bem a diferentes ambientes, mas precisa de companhia constante devido ao seu forte vínculo com a família.",
    image: "/images/breeds/griffon-de-bruxelas.jpg",
    energyLevel: "Médio a Alto",
    coat: "Áspero ou Liso",
    trainability: 7,
    childFriendly: 6,
    exerciseNeeds: 4,
    groomingNeeds: 6,
    shedding: 3,
    breeders: [
      {
        name: "Canil Brussels Elite",
        location: "São Paulo, SP",
        website: "https://www.brusselselite.com.br",
      },
      {
        name: "Griffon Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.griffonbrasil.com.br",
      },
    ],
  },
  {
    id: 34,
    name: "Mastiff Inglês",
    size: "Gigante",
    purpose: "Guarda e Proteção",
    description:
      "O Mastiff Inglês é um dos maiores cães do mundo, com presença imponente e dignidade natural. Apesar do tamanho intimidador, é conhecido por seu temperamento gentil e calmo. Extremamente leal à família, é um guardião natural, mas paciente e afetuoso com os membros da família.",
    image: "/images/breeds/mastiff-ingles.jpg",
    energyLevel: "Baixo a Médio",
    coat: "Curto",
    trainability: 6,
    childFriendly: 7,
    exerciseNeeds: 4,
    groomingNeeds: 3,
    shedding: 6,
    breeders: [
      {
        name: "Canil Old English Mastiff",
        location: "São Paulo, SP",
        website: "https://www.oldenglishmastiff.com.br",
      },
      {
        name: "Mastiff Brasil",
        location: "Rio Grande do Sul, RS",
        website: "https://www.mastiffbrasil.com.br",
      },
    ],
  },
  {
    id: 35,
    name: "Mastino Napolitano",
    size: "Grande",
    purpose: "Guarda e Proteção",
    description:
      "O Mastino Napolitano é um cão imponente e massivo, com aparência única devido às suas dobras de pele características. Originário da Itália, é um guardião nato, leal e protetor. Apesar da aparência intimidadora, é afetuoso com a família, mas reservado com estranhos.",
    image: "/images/breeds/mastino-napolitano.jpg",
    energyLevel: "Baixo a Médio",
    coat: "Curto",
    trainability: 5,
    childFriendly: 6,
    exerciseNeeds: 4,
    groomingNeeds: 5,
    shedding: 5,
    breeders: [
      {
        name: "Canil Napoli Mastini",
        location: "São Paulo, SP",
        website: "https://www.napolimastini.com.br",
      },
      {
        name: "Mastino Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.mastinobrasil.com.br",
      },
    ],
  },
  {
    id: 36,
    name: "Whippet",
    size: "Médio",
    purpose: "Companhia e Esporte",
    description:
      "O Whippet é um cão elegante e atlético, conhecido como o 'galgo em miniatura'. Extremamente veloz em corridas curtas, em casa é um cão tranquilo, afetuoso e de baixa manutenção. Adapta-se bem a apartamentos, mas precisa de oportunidades para correr em áreas seguras.",
    image: "/images/breeds/whippet.jpg",
    energyLevel: "Médio",
    coat: "Curto",
    trainability: 7,
    childFriendly: 8,
    exerciseNeeds: 7,
    groomingNeeds: 1,
    shedding: 2,
    breeders: [
      {
        name: "Canil Whippet Speed",
        location: "São Paulo, SP",
        website: "https://www.whippetspeed.com.br",
      },
      {
        name: "Whippet Brasil",
        location: "Rio de Janeiro, RJ",
        website: "https://www.whippetbrasil.com.br",
      },
    ],
  },
  {
    id: 37,
    name: "Borzoi",
    size: "Grande",
    purpose: "Companhia e Esporte",
    description:
      "O Borzoi, também conhecido como Galgo Russo, é um cão elegante e aristocrático, com pelagem longa e sedosa. Originalmente criado para caçar lobos na Rússia, hoje é principalmente um cão de companhia. Calmo e gentil em casa, mantém seu instinto de perseguição ao ar livre.",
    image: "/images/breeds/borzoi.jpg",
    energyLevel: "Médio",
    coat: "Longo e Sedoso",
    trainability: 5,
    childFriendly: 7,
    exerciseNeeds: 6,
    groomingNeeds: 7,
    shedding: 5,
    breeders: [
      {
        name: "Canil Russian Wolfhound",
        location: "São Paulo, SP",
        website: "https://www.russianwolfhound.com.br",
      },
      {
        name: "Borzoi Elite Brasil",
        location: "Minas Gerais, MG",
        website: "https://www.borzoielite.com.br",
      },
    ],
  },
  {
    id: 38,
    name: "Basenji",
    size: "Pequeno a Médio",
    purpose: "Companhia",
    description:
      "O Basenji é conhecido como o 'cão que não late', emitindo sons únicos semelhantes a yodels. Originário da África, é um cão independente, inteligente e curioso, com aparência elegante e comportamento semelhante ao de gatos. Limpo e de baixo odor, requer um dono que entenda sua natureza independente.",
    image: "/images/breeds/basenji.jpg",
    energyLevel: "Alto",
    coat: "Curto",
    trainability: 4,
    childFriendly: 6,
    exerciseNeeds: 7,
    groomingNeeds: 2,
    shedding: 2,
    breeders: [
      {
        name: "Canil Basenji Brasil",
        location: "São Paulo, SP",
        website: "https://www.basenjibrasil.com.br",
      },
      {
        name: "African Hound",
        location: "Brasília, DF",
        website: "https://www.africanhound.com.br",
      },
    ],
  },
]
